### PR TITLE
Fix capitalizing symbols which partially match a keyword

### LINKED ISSUE #50: variable name with "_" get capitalized.
original:
```
select max(peer_group) as peer_group
from apple
```
becomes
```
SELECT MAX(PEER_GROUP) AS PEER_GROUP
FROM apple
```

### PR DESCRIPTION
**Pull request by davidshepherd7**
Closes #50 

Unfortunately I couldn't get a failing test for this, not sure why.

### CODE REVIEW

**Comment by davidshepherd7** [comment]
Urgh, this seems to have broken some other tests though... 

They seem to be yet another case of the tests failing but it actually working :(

**Comment by Trevoke** [comment]
After merging this locally, there definitely is a new failing test. I don't know why this occurs, but now we can probably bring in @rejeep and ask him since there's this thing we can't get to fail, and https://github.com/Trevoke/sqlup-mode.el/issues/49 where the test fails but the code works in emacs.

**Comment by davidshepherd7** [comment]
So, I just found that we weren't actually turning on sql mode in the tests! With that fixed things seem to make sense again :)

**Comment by davidshepherd7** [comment]
Closing to recreate a cleaned up version on a non-master branch.

**Comment by rejeep** [comment]
Did you sort everything out?

**Comment by Trevoke** [comment]
@rejeep Hi, it looks like we did, yes, thanks. The only question I had for you was, in ecukes, what is the default major mode for the created buffers for the test?

**Comment by rejeep** [comment]
@Trevoke Should be `fundamental-mode` unless you add some custom code yourself. Ecukes does not do anything magic, it only starts Emacs.

**Comment by Trevoke** [comment]
OK, thank you!

**Pull request closed without merging**
